Cyb3rWard0g/HELK

README.md
docker-compose.yml
enrichments/ACE/logstash/03-ace-rabbitmq-input.conf

Added docker volume for elasticsearch data to persist
Added documentation for increasing memory of elasticsearch
Updated ACE logstash input for durable queue

Update ACE enrichment and add docker volumes

---

docker-compose.yml

Fixed typo in docker-compose volume section

Fixed typo

---

README.md
helk-elk/Dockerfile
helk-elk/scripts/elk-kibana-setup.sh

Sigma searches are now preloaded in Kibana.

Sigma integration

---

README.md
helk-elk/Dockerfile
helk-elk/scripts/elk-kibana-setup.sh

Revert "Sigma integration"

---

docker/helk_update.sh

Slight improvement in the HELK Update check
Bug Fix
Change Directory to docker/ and run sudo ./helk_update.sh
**Questions:**

Minor improvement to update check

---

docker/helk_update.sh

To revise the update script, align it with the Christmas Release
[Bug Fix]
Change directory to docker/ and run `sudo ./helk_update.sh`
**Questions:**

Revise update script to align with Christmas Release

---

docker/helk_update.sh

Added check to validate if PWD is a valid git repository, and if not, refresh HELK
Bug Fix for git problems mentioned in #136 
Remove ```.git``` repository in HELK directory, then ```cd docker/``` and ```sudo ./helk_update.sh```
**Questions:**

Added git checks for stable update experience

---

docker/helk_update.sh

Noticed that there were a few differences between the subscription and build choice menu in the 2 scripts, I have updated them in the update script.
Bug Fix
Change pwd to ```{HELK directory}/docker``` and run ```sudo ./helk_update.sh```
**Questions:**

Made subscription and build choice menu same as install script

---

docker/helk-logstash/pipeline/2511-winevent-powershell-filter.conf

typo, fixes script rename to correctly user powershell.script.name now

---

docker/helk-elasticsearch/scripts/elasticsearch-entrypoint.sh
docker/helk-logstash/output_templates/60-winevent-sysmon-template.json
docker/helk-logstash/pipeline/1531-winevent-sysmon-filter.conf

Logstash:
fix https://github.com/Cyb3rWard0g/HELK/issues/278
fix https://github.com/Cyb3rWard0g/HELK/issues/277
fix https://github.com/Cyb3rWard0g/HELK/issues/274
fix https://github.com/Cyb3rWard0g/HELK/issues/273
Elasticsearch:
fix https://github.com/Cyb3rWard0g/HELK/issues/275
Fix a few open issues and a bug
Bug Fix and Feature Request
**Questions:**

Logstash Pipeline and ES Memory

---

docker/helk-logstash/pipeline/2511-winevent-powershell-filter.conf
docker/helk-logstash/pipeline/2512-winevent-security-schtasks-filter.conf

scheduled task and PS

---

docker/helk-logstash/pipeline/1531-winevent-sysmon-filter.conf

Added the new fields and DNSEvent type for the changes for Sysmon 10.
https://medium.com/@olafhartong/sysmon-10-0-new-features-and-changes-e82106f2e00
Feature Request
Sysmon 10 should be installed on the host. 
`OriginalFileName` can be confirmed with events 1 (process create), 7 (module load)
`EventType` can be confirmed with events 17, 18 (pipe created and connected).
DNSEvent can be confirmed with new generated event 22 (ping www.google.com will work)
**Questions:**

[Feature Request] Added Sysmon 10 new fields and DNSEvent type.

---

docker/helk-logstash/pipeline/1542-winevent-process-ids-conversions.conf
docker/helk_docker_install.sh
docker/helk_install.sh

- install latest docker
- process granted as decimal

Fix #186 and Fix #271

---

docker/helk-elastalert/Dockerfile
docker/helk-kibana-analysis-alert-basic.yml
docker/helk-kibana-analysis-alert-trial.yml
docker/helk-kibana-notebook-analysis-alert-basic.yml
docker/helk-kibana-notebook-analysis-alert-trial.yml

upgrades elastalert which now supports elastic’s 7.x

Temporary elastalert hotfix

---

docker/helk-elastalert/scripts/pull-sigma.sh

improves ordering of sigmac configuration to allow event more HELK/OSSEM specific ordering

correct OSSEM <> SIGMAC ordering

---

docker/helk-logstash/pipeline/9990-winevent-catchall-output.conf
docker/helk-logstash/pipeline/9998-catch_all-output.conf

implement windows event channel catch all before a general ALL catchall.

windows catchall, before ALL catchall

---

docker/helk-logstash/pipeline/8112-dst-ip-filter.conf
docker/helk-logstash/pipeline/8113-src-ip-filter.conf
docker/helk-logstash/pipeline/8114-dst-nat-ip-filter.conf
docker/helk-logstash/pipeline/8115-src-nat-ip-filter.conf

keep all geo fields despite taxonomy/schema, for continuity if upstream(NON …

geo fields non schema

---

winlogbeat/winlogbeat.yml

re add winlogbeat config example

winlogbeat configuration example

---

docker/helk-logstash/pipeline/1521-winevent-conversions-ip-conversions-basic-filter.conf
docker/helk-logstash/pipeline/1531-winevent-sysmon-filter.conf
docker/helk-logstash/pipeline/1532-winevent-security-filter.conf
docker/helk-logstash/pipeline/1533-winevent-system-filter.conf
docker/helk-logstash/pipeline/1534-winevent-application-filter.conf
docker/helk-logstash/pipeline/1535-winevent-wmiactivity-filter.conf
docker/helk-logstash/pipeline/1545-winevent-security-conversions.conf
docker/helk-logstash/pipeline/2512-winevent-security-schtasks-filter.conf
docker/helk-logstash/pipeline/9950-winevent-sysmon-output.conf
docker/helk-logstash/pipeline/9951-winevent-security-output.conf
docker/helk-logstash/pipeline/9952-winevent-system-output.conf
docker/helk-logstash/pipeline/9953-winevent-application-output.conf
docker/helk-logstash/pipeline/9955-winevent-wmiactivity-output.conf

fix channel casing in field log_name
[Bug Fix] or [Feature Request]
bug fix
Specific steps, configs and images if available
send windows logs
Hey Roberto, it was nice to meet you today at ATT&CK Conference. You mentioned some issues with log_name and that somebody was working on it. However i decided to just do it until that is done. Let me know if this works.

change channel values

---

docker/helk-logstash/pipeline/1521-winevent-conversions-ip-conversions-basic-filter.conf

hotfix 20191107

---

.github/ISSUE_TEMPLATE/Custom.md

update issue template

---

docker/helk_update.sh

Bring helk_update.sh script up-to-date with current release
Bug Fix
In terminal, change directory to `$HELK_DIR/docker` and run `sudo bash helk_update.sh`
**Questions:**

Updated helk_update.sh

---

docker/helk_update.sh

exit if local git is modified and not commited

update helk script tweak

---

docker/helk-kafka-base/Dockerfile

make scala download link https and fix incorrect version that caused a 404 link/error
fixes #400

scala download

---

docker/helk-kibana/scripts/kibana-entrypoint.sh

continue enhancing kibana start/scripts

Scripts helk install and update

---

docker/helk_install.sh
docker/helk_remove_containers.sh
docker/helk_setup_firewall.sh

final testing for CentOS with selinux enabled.. Verified install a few times with a few people..
additionally check docker is started before continuing on all platforms...

centos and minor install tweak

---

.gitignore

ignore files commonly for backup/testing, may help later upgrading/up…

helk os/core

---

docker/helk_install.sh

quick fix calling function that didn't exist
fixes #464

hotfix, function missing

---

docs/architecture/kibana.md

Fixed broken image URIs in kibana.md documentation
[Bug Fix]
Should not need testing
**Questions:**

Fixed kibana.md image URIs

---

docker/helk-kibana-analysis-alert-basic.yml
docker/helk-kibana-analysis-basic.yml
docker/helk-kibana-notebook-analysis-alert-basic.yml
docker/helk-kibana-notebook-analysis-basic.yml

Title says it all
[Bug Fix] or [Feature Request]
Feature request. This version has the ability to utilize multi-joins in KSQL
I tested on my custom build
**Questions:**

Update KSQL to KSQLDB

---

docker/helk-logstash/pipeline/9998-catch_all-output.conf

causes way too much unnecessary confusion

get rid of indexme

---

docker/helk-logstash/pipeline/9998-catch_all-output.conf

packetbeat, auditbeat, metricbeat. add comment for what is parsed filebeat

add more specific outputs
